apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURVdwpNREk0TkRWYUZ3MDBNakE0TURVd01ESTRORFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERXRWbzJuL0EyMFB6b1pMQndwSG9jN29BUi9uNmthM2U5RWZHR1lnYlNmL01kTkk2SQpZbEp4QnorQkNDVlVmYUp2WEFxTmVlbUhFSWRCN0FEK1g3NSthS0RBKytBQmV0YnJNcGtVdVJFQ010QWpIdU1yCmFDdEtnN0ZvYXVvaW9WY3AwS05EMzJ1RFd4ZVNydkVXMWo4QkxaSys0Q05zb3h1Q2NVQm1OSXAyd21waHN2bXoKb2Y2ZnRyR3BxdjgvVHQ3M09lUmo5MHZKYzFpMjBHck9LSFM2UFZYYTFma0NXdnZTWEZuK0FjeGhieVlMNHJYbwplS3hodkkzNXpzeW5ZT281RGZVeTN2R2Y4eHB2SXNkS1pkTzFBM05oT2pqaEF4QWRVenY5UHpQcEpwdWJSN3ArCjlyQXR5Tm82eklCaWg4VDJZQ0VXbmNxQVhKU0FFSzlmMFhOSEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNJME95Yy83Q2drcXgwNWdDQgpibXVWdEs1d3FUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUTzZ2aFF5M3BZVGZrRkcwSnpBOFpWYmcxdkhCCngzTWJZNDJGR3UrNFE5QXJGQThzeUN4NGNRcFY3ZUhXcndWaDNLKzZ0dGQ3Y3BJRm1ERDkxQk9MaThKbXFUalYKcmdrbDk4MTArUm5YQjI4SC8zcmxYa1VDeFhJQTVhb0hDaEFSUkRTR01EQXV1U2NjSWdNa1lWRnhxTWxKNGhJRQo3RnR3citGNUZZM1BId0xZMWpCS1dtMis5cjQ3R01EY2tITTlXL2NEYzdFTCtzNWNnT3hrcjE1UHo5N1c2WHd6CngxTlN6aVNaTWt4MXNlREx5UkJhRlM3YmRBQXZRZ29hblhhdkV2RlpnQ0ZEb25WL05Bbi9id3NqVHBYVGdwNGoKRkVJTm1HTlFqTUtNRGdaTUpSd0ZQUWVIVDZyWlVWTjVIWWZXWkUzSHUxZmxhekppbDJRVnVXWklxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://22fb965f-57aa-462c-a504-712b65adbcd7.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa
    user: do-nyc1-k8s-iniciativa-admin
  name: do-nyc1-k8s-iniciativa
current-context: do-nyc1-k8s-iniciativa
users:
- name: do-nyc1-k8s-iniciativa-admin
  user:
    token: dop_v1_79e1059dbfc2c19bd37f7aa26aee988ef20737f302e244b20e7ccc57ad5e6bde
