  name: CI-DI

  on:
  push:
    branches: [ "main" ]

    CI:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Docker Login
          uses: docker/login-action@v2.0.0
          with:
            username: ${{secrets.DOCKERHUB_USER}}
            password: ${{secrets.DOCKERHUB_PWD}}

        - name: Build and push Docker images
          uses: docker/build-push-action@v3.1.0
          with:
            file: ./src/dockerfile
            context: ./src
            push: true
            tags:  | 
              rodrigoserieiro/kube-news:latest
              rodrigoserieiro/kube-news:${{github.run_number}}
    CD:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Kubernetes Set Context
          uses: Azure/k8s-set-context@v3.0
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.k8s_CONFIG}}
        - name: Deploy to Kubernetes cluster
          uses: Azure/k8s-deploy@v4.3
          with:
            imagens: rodrigoserieiro/kube-news:${{github.run_number}}
            manifestes: |
            k8s/deployment.yaml
